"""Compose prompts/system_<version>.md from prompts/components/*.md.

The component files are the source of truth. Each version is an ordered list of
component names. Run this whenever a component changes:

    uv run python prompts/compose.py
"""

from pathlib import Path

HERE = Path(__file__).parent
COMPONENTS = HERE / "components"

VERSIONS: dict[str, list[str]] = {
    # v1: baseline. safety.md already carries injection / prompt-exfil rules; the
    # red-team pass decides whether v2 needs a hardened variant.
    "v1": ["persona", "scope", "grounding", "safety", "output_format", "fewshot"],
    # v1_nofs: identical to v1 without the few-shot exemplars, for the A/B that
    # quantifies what the exemplars buy (docs/DESIGN.md section 7).
    "v1_nofs": ["persona", "scope", "grounding", "safety", "output_format"],
    # v2: red-team hardening. Four components get a _v2 variant (v1's stay frozen
    # so its baseline stays reproducible). Changes + attack ids in
    # prompts/CHANGELOG.md:
    #   output_format_v2 - every refusal must go through final_answer  (A5/A6/A10)
    #   safety_v2        - no tool/capability enumeration; answer the real
    #                      question despite an injected instruction     (Q2, A7)
    #   grounding_v2     - correct false premises even inside a refusal  (A4)
    #   fewshot_v2       - + tool-enumeration and injected-instruction exemplars
    "v2": ["persona", "scope", "grounding_v2", "safety_v2", "output_format_v2", "fewshot_v2"],
}

SEP = "\n\n---\n\n"


def compose(version: str) -> str:
    names = VERSIONS[version]
    parts = [(COMPONENTS / f"{n}.md").read_text().strip() for n in names]
    header = f"<!-- generated by prompts/compose.py from: {', '.join(names)} -->\n"
    return header + SEP.join(parts) + "\n"


def main() -> None:
    for version in VERSIONS:
        out = HERE / f"system_{version}.md"
        text = compose(version)
        out.write_text(text)
        print(f"wrote {out.name}  ({len(text)} chars, {len(VERSIONS[version])} components)")


if __name__ == "__main__":
    main()
